export const FETCH_STUDENT_REQUEST = 'FETCH_STUDENT_REQUEST';
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS';
export const FETCH_STUDENT_FAIL = 'FETCH_STUDENT_FAIL';

export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';

export const DELE_STUDENT_REQUEST = 'DELE_STUDENT_REQUEST';
export const DELE_STUDENT_SUCCESS = 'DELE_STUDENT_SUCCESS';
export const DELE_STUDENT_FAIL = 'DELE_STUDENT_FAIL';